
import java.io.IOException;
import java.io.RandomAccessFile;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author andre
 */
public class Cardapio extends javax.swing.JFrame {

    String pedido = "";
    int cont = 0;

    /**
     * Creates new form NewJFrame
     */
    public Cardapio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel10 = new javax.swing.JPanel();
        jcb_gengibre = new javax.swing.JCheckBox();
        jcb_wasabi = new javax.swing.JCheckBox();
        jcb_tartaro = new javax.swing.JCheckBox();
        jcb_alhopimenta = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jrb_ebifurai = new javax.swing.JRadioButton();
        jrb_karague = new javax.swing.JRadioButton();
        jrb_peixefrito = new javax.swing.JRadioButton();
        jrb_yakisoba = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jb_calcular = new javax.swing.JButton();
        jb_limparPedido = new javax.swing.JButton();
        jb_sair = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jtf_total = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jrb_djow = new javax.swing.JRadioButton();
        jrb_temaki = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jtf_cliente = new javax.swing.JTextField();
        jtf_rua = new javax.swing.JTextField();
        jtf_numero = new javax.swing.JTextField();
        jtf_bairro = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jtf_complemento = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jtf_entregador = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jtf_trocoPara = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jtf_totalTroco = new javax.swing.JTextField();
        jb_calcularTroco = new javax.swing.JButton();
        jb_gerarEntrega = new javax.swing.JButton();
        jb_limparEntraga = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jtf_telefone = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hara Sushi");
        setAutoRequestFocus(false);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.darkGray);
        setIconImages(null);

        jPanel10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.setToolTipText("");

        jcb_gengibre.setText("GENGIBRE ------R$2,00");
        jcb_gengibre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_gengibreActionPerformed(evt);
            }
        });

        jcb_wasabi.setText("WASABI------R$2,00");
        jcb_wasabi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_wasabiActionPerformed(evt);
            }
        });

        jcb_tartaro.setText("TÁRTARO------R$2,00");
        jcb_tartaro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_tartaroActionPerformed(evt);
            }
        });

        jcb_alhopimenta.setText("ALHO COM PIMENTA------R$2,00");
        jcb_alhopimenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_alhopimentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcb_wasabi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcb_alhopimenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcb_gengibre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcb_tartaro, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jcb_alhopimenta, jcb_gengibre, jcb_tartaro, jcb_wasabi});

        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcb_gengibre)
                .addGap(18, 18, 18)
                .addComponent(jcb_wasabi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jcb_tartaro)
                .addGap(18, 18, 18)
                .addComponent(jcb_alhopimenta)
                .addContainerGap())
        );

        jPanel10Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jcb_alhopimenta, jcb_gengibre, jcb_tartaro, jcb_wasabi});

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setToolTipText("");

        buttonGroup1.add(jrb_ebifurai);
        jrb_ebifurai.setText("EBI FURAI - Camarão Empanado ------- R$105,00");
        jrb_ebifurai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_ebifuraiActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrb_karague);
        jrb_karague.setText("KARAGUE - 500G - Frango Frito -------- R$28,00");

        buttonGroup1.add(jrb_peixefrito);
        jrb_peixefrito.setText("PEIXE FRITO 500G----------------------- R$34,00");

        buttonGroup1.add(jrb_yakisoba);
        jrb_yakisoba.setText("YAKISOBA 500G ------------------------- R$25,00");
        jrb_yakisoba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_yakisobaActionPerformed(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yakisoba.png"))); // NOI18N

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/peixefrito.png"))); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/karague.png"))); // NOI18N

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ebifurai.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrb_peixefrito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jrb_yakisoba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(37, 37, 37))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jrb_karague, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(26, 26, 26))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jrb_ebifurai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(26, 26, 26))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jrb_ebifurai)
                        .addGap(66, 66, 66)
                        .addComponent(jrb_karague)
                        .addGap(66, 66, 66)
                        .addComponent(jrb_peixefrito)
                        .addGap(64, 64, 64)
                        .addComponent(jrb_yakisoba)
                        .addGap(40, 40, 40))))
        );

        jLabel4.setText("INDIVIDUAL");
        jLabel4.setToolTipText("");

        jb_calcular.setText("Calcular");
        jb_calcular.setToolTipText("");
        jb_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_calcularActionPerformed(evt);
            }
        });

        jb_limparPedido.setText("Limpar");
        jb_limparPedido.setToolTipText("");
        jb_limparPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_limparPedidoActionPerformed(evt);
            }
        });

        jb_sair.setText("Sair");
        jb_sair.setToolTipText("");
        jb_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_sairActionPerformed(evt);
            }
        });

        jLabel2.setText("OPÇÕES DE CREME");
        jLabel2.setToolTipText("");

        jtf_total.setText("0");
        jtf_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_totalActionPerformed(evt);
            }
        });

        jLabel3.setText("PORÇÕES");
        jLabel3.setToolTipText("");

        jLabel12.setText("Total R$");

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setToolTipText("");

        buttonGroup2.add(jrb_djow);
        jrb_djow.setText("DJOW - Salmão --------- R$6,30");
        jrb_djow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_djowActionPerformed(evt);
            }
        });

        buttonGroup2.add(jrb_temaki);
        jrb_temaki.setText("TEMAKI - Salmão ------- R$19,00");
        jrb_temaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_temakiActionPerformed(evt);
            }
        });

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/temaki.png"))); // NOI18N

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/djow.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrb_temaki))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrb_djow)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel18))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jrb_temaki)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jrb_djow))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Cliente:");

        jLabel5.setText("Rua:");

        jLabel20.setText("Bairro:");

        jLabel21.setText("N°:");

        jtf_rua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_ruaActionPerformed(evt);
            }
        });

        jLabel22.setText("Complemento:");

        jLabel23.setText("Entregador:");

        jLabel24.setText("Troco para:");

        jtf_trocoPara.setText("0");
        jtf_trocoPara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_trocoParaActionPerformed(evt);
            }
        });

        jLabel25.setText("R$");

        jLabel27.setText("Total troco:");

        jtf_totalTroco.setText("0");

        jb_calcularTroco.setText("Calcular");
        jb_calcularTroco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_calcularTrocoActionPerformed(evt);
            }
        });

        jb_gerarEntrega.setText("Gerar entrega");
        jb_gerarEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_gerarEntregaActionPerformed(evt);
            }
        });

        jb_limparEntraga.setText("Limpar");
        jb_limparEntraga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_limparEntragaActionPerformed(evt);
            }
        });

        jLabel29.setText("R$");

        jLabel30.setText("Telefone:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtf_telefone)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jb_gerarEntrega, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(4, 4, 4)
                        .addComponent(jb_limparEntraga))
                    .addComponent(jtf_cliente)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_rua, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jtf_numero)))
                    .addComponent(jtf_entregador)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_trocoPara, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addGap(79, 79, 79))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_totalTroco, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jb_calcularTroco))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jtf_complemento))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addComponent(jtf_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_rua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_complemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_trocoPara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(jtf_totalTroco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_calcularTroco)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtf_entregador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_limparEntraga)
                    .addComponent(jb_gerarEntrega))
                .addGap(9, 9, 9))
        );

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logohara.png"))); // NOI18N

        jLabel28.setText("ENTREGA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_total)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jb_calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addComponent(jLabel2))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jb_limparPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jb_sair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jLabel3)
                        .addGap(210, 210, 210)
                        .addComponent(jLabel4)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel28)
                        .addGap(137, 137, 137))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(433, 433, 433))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jb_sair)
                            .addComponent(jb_limparPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jb_calcular)
                            .addComponent(jtf_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(10, 10, 10)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_calcularActionPerformed
        double total = 0;
        if (jcb_alhopimenta.isSelected()) {
            total += 2;
            pedido += jcb_alhopimenta.getText() + "\n";
        }
        if (jcb_gengibre.isSelected()) {
            total += 2;
            pedido += jcb_gengibre.getText() + "\n";
        }
        if (jcb_tartaro.isSelected()) {
            total += 2;
            pedido += jcb_tartaro.getText() + "\n";
        }
        if (jcb_wasabi.isSelected()) {
            total += 2;
            pedido += jcb_wasabi.getText() + "\n";
        }
        if (jrb_djow.isSelected()) {
            total += 6.30;
            pedido += jrb_djow.getText() + "\n";
        }
        if (jrb_ebifurai.isSelected()) {
            total += 105;
            pedido += jrb_ebifurai.getText() + "\n";
        }
        if (jrb_karague.isSelected()) {
            total += 28;
            pedido += jrb_karague.getText() + "\n";
        }
        if (jrb_peixefrito.isSelected()) {
            total += 34;
            pedido += jrb_peixefrito.getText() + "\n";
        }
        if (jrb_temaki.isSelected()) {
            total += 19;
            pedido += jrb_temaki.getText() + "\n";
        }
        if (jrb_yakisoba.isSelected()) {
            total += 25;
            pedido += jrb_yakisoba.getText() + "\n";
        }

        jtf_total.setText(String.valueOf(total));

        // TODO add your handling code here:
    }//GEN-LAST:event_jb_calcularActionPerformed

    private void jrb_temakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_temakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrb_temakiActionPerformed

    private void jrb_djowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_djowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrb_djowActionPerformed

    private void jtf_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_totalActionPerformed

    private void jb_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_sairActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_sairActionPerformed

    private void jb_limparPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_limparPedidoActionPerformed
        // TODO add your handling code here:
        jtf_total.setText("");

        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();

        jcb_alhopimenta.setSelected(false);
        jcb_gengibre.setSelected(false);
        jcb_tartaro.setSelected(false);
        jcb_wasabi.setSelected(false);
    }//GEN-LAST:event_jb_limparPedidoActionPerformed

    private void jcb_alhopimentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_alhopimentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_alhopimentaActionPerformed

    private void jcb_tartaroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_tartaroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_tartaroActionPerformed

    private void jcb_wasabiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_wasabiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_wasabiActionPerformed

    private void jcb_gengibreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_gengibreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_gengibreActionPerformed

    private void jtf_ruaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_ruaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_ruaActionPerformed

    private void jb_gerarEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_gerarEntregaActionPerformed
        String entrega = "Dados da entrega:\n" + "Nome do Cliente" + jtf_cliente.getText()
                + "\nEndereço: " + jtf_rua.getText() + ", " + jtf_numero.getText() + " - " + jtf_bairro.getText()
                + "\nComplemento: " + jtf_complemento.getText()
                + "\nTroco para: " + jtf_trocoPara.getText()
                + "\nTroco: " + jtf_totalTroco.getText()
                + "\nEntregador: " + jtf_entregador.getText()
                + "\n\n Pedido:\n"
                + pedido;

        byte[] buffer = entrega.getBytes();

        try {
            cont++;
            RandomAccessFile raf = new RandomAccessFile("src/Pedidos/Pedido" + cont + ".txt", "rw");
            raf.write(buffer);

        } catch (IOException ex) {
            ex.printStackTrace();
        }

        pedido = "";

        jtf_bairro.setText("");
        jtf_cliente.setText("");
        jtf_complemento.setText("");
        jtf_entregador.setText("");
        jtf_numero.setText("");
        jtf_rua.setText("");
        jtf_telefone.setText("");
        jtf_totalTroco.setText("");
        jtf_trocoPara.setText("");
        jtf_total.setText("");

        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();

        jcb_alhopimenta.setSelected(false);
        jcb_gengibre.setSelected(false);
        jcb_tartaro.setSelected(false);
        jcb_wasabi.setSelected(false);
    }//GEN-LAST:event_jb_gerarEntregaActionPerformed

    private void jb_calcularTrocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_calcularTrocoActionPerformed

        double trocoPara = 0;
        trocoPara = Double.parseDouble(jtf_trocoPara.getText());
        
        if (trocoPara > 0) {
            jtf_totalTroco.setText(String.valueOf(Double.parseDouble(jtf_total.getText()) - trocoPara));
        }
    }//GEN-LAST:event_jb_calcularTrocoActionPerformed

    private void jrb_yakisobaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_yakisobaActionPerformed

    }//GEN-LAST:event_jrb_yakisobaActionPerformed

    private void jrb_ebifuraiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_ebifuraiActionPerformed

    }//GEN-LAST:event_jrb_ebifuraiActionPerformed

    private void jb_limparEntragaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_limparEntragaActionPerformed

        jtf_bairro.setText("");
        jtf_cliente.setText("");
        jtf_complemento.setText("");
        jtf_entregador.setText("");
        jtf_numero.setText("");
        jtf_rua.setText("");
        jtf_telefone.setText("");
        jtf_totalTroco.setText("");
        jtf_trocoPara.setText("");
    }//GEN-LAST:event_jb_limparEntragaActionPerformed

    private void jtf_trocoParaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_trocoParaActionPerformed
        jtf_trocoPara.setText("0");        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_trocoParaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cardapio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cardapio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jb_calcular;
    private javax.swing.JButton jb_calcularTroco;
    private javax.swing.JButton jb_gerarEntrega;
    private javax.swing.JButton jb_limparEntraga;
    private javax.swing.JButton jb_limparPedido;
    private javax.swing.JButton jb_sair;
    private javax.swing.JCheckBox jcb_alhopimenta;
    private javax.swing.JCheckBox jcb_gengibre;
    private javax.swing.JCheckBox jcb_tartaro;
    private javax.swing.JCheckBox jcb_wasabi;
    private javax.swing.JRadioButton jrb_djow;
    private javax.swing.JRadioButton jrb_ebifurai;
    private javax.swing.JRadioButton jrb_karague;
    private javax.swing.JRadioButton jrb_peixefrito;
    private javax.swing.JRadioButton jrb_temaki;
    private javax.swing.JRadioButton jrb_yakisoba;
    private javax.swing.JTextField jtf_bairro;
    private javax.swing.JTextField jtf_cliente;
    private javax.swing.JTextField jtf_complemento;
    private javax.swing.JTextField jtf_entregador;
    private javax.swing.JTextField jtf_numero;
    private javax.swing.JTextField jtf_rua;
    private javax.swing.JTextField jtf_telefone;
    private javax.swing.JTextField jtf_total;
    private javax.swing.JTextField jtf_totalTroco;
    private javax.swing.JTextField jtf_trocoPara;
    // End of variables declaration//GEN-END:variables
}
