/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import dao.ConsumoDAO;
import java.util.List;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;

/**
 *
 * @author andre
 */
public class ConsumoForm extends javax.swing.JFrame {

    private ConsumoDAO consumoDao = new ConsumoDAO();
    private List<Cliente> clientes;
    private Cliente clienteSelecionado;

    public ConsumoForm() {
        initComponents();
        atualizarTabela();
        habilitarFormulario(false);
        atualizarBotao(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_excluir = new javax.swing.JButton();
        btn_alterar = new javax.swing.JButton();
        btn_salvar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_cliente = new javax.swing.JTable();
        jtf_pesquisa = new javax.swing.JTextField();
        btn_pesquisar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btn_cadastrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txf_nome = new javax.swing.JTextField();
        txf_sexo = new javax.swing.JTextField();
        txf_endereco = new javax.swing.JTextField();
        txf_cep = new javax.swing.JTextField();
        txf_bairro = new javax.swing.JTextField();
        txf_cpf = new javax.swing.JTextField();
        txf_nascimento = new javax.swing.JTextField();
        txf_dataVencimento = new javax.swing.JTextField();
        txf_unidadeConsumidora = new javax.swing.JTextField();
        txf_kwh = new javax.swing.JTextField();
        txf_valorTotal = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        txf_email = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_excluir.setText("Excluir");
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        btn_alterar.setText("Alterar");
        btn_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alterarActionPerformed(evt);
            }
        });

        btn_salvar.setText("Salvar");
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        tabela_cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "CPF", "UC", "Vencimento", "KW/h", "Valor Total"
            }
        ));
        jScrollPane1.setViewportView(tabela_cliente);

        jtf_pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_pesquisaActionPerformed(evt);
            }
        });

        btn_pesquisar.setText("Pesquisar");
        btn_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pesquisarActionPerformed(evt);
            }
        });

        jLabel5.setText("Busca");

        btn_cadastrar.setText("Cadastrar");
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome");

        jLabel2.setText("Sexo");

        jLabel3.setText("Endereço");

        jLabel4.setText("CEP");

        jLabel6.setText("Bairro");

        jLabel7.setText("CPF");

        jLabel8.setText("Nascimento");

        jLabel9.setText("Data de Vencimento");

        jLabel10.setText("Unidade Consumidora");

        jLabel11.setText("KW/h");

        jLabel12.setText("Valor Total");

        txf_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_nomeActionPerformed(evt);
            }
        });

        txf_sexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_sexoActionPerformed(evt);
            }
        });

        txf_cep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_cepActionPerformed(evt);
            }
        });

        txf_bairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_bairroActionPerformed(evt);
            }
        });

        txf_cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_cpfActionPerformed(evt);
            }
        });

        jLabel13.setText("R$");

        jLabel14.setText("Consumo Energia");

        jLabel15.setText("E-mail");

        txf_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_emailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jLabel14))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_pesquisa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_pesquisar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txf_dataVencimento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txf_valorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txf_sexo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txf_endereco))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txf_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txf_nascimento))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txf_cep, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txf_bairro))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txf_unidadeConsumidora, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txf_kwh, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txf_email))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(btn_cadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_cancelar)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txf_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txf_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txf_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(txf_nascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txf_cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txf_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txf_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txf_unidadeConsumidora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(txf_kwh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(txf_valorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(txf_dataVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_pesquisar)
                    .addComponent(jtf_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_cadastrar)
                        .addComponent(btn_excluir)
                        .addComponent(btn_alterar)
                        .addComponent(btn_salvar)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel10, jLabel11, jLabel12, jLabel2, jLabel3, jLabel4, jLabel6, jLabel7, jLabel8, jLabel9});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        int linha = tabela_cliente.getSelectedRow();
        if (linha < 0) {
            JOptionPane.showMessageDialog(null, "Selecione um cliente!", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }

        clienteSelecionado = clientes.get(linha);
        try {

            consumoDao.remover(clienteSelecionado.getId_cliente());
            JOptionPane.showMessageDialog(null, "Pessoa excluida!");

            atualizarTabela();

        } catch (SQLException ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_btn_excluirActionPerformed

    private void jtf_pesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_pesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_pesquisaActionPerformed

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed

        limparCampos();

        clienteSelecionado = null;
        atualizarBotao(false);
        habilitarFormulario(true);
        txf_nome.requestFocus();

    }//GEN-LAST:event_btn_cadastrarActionPerformed

    private void limparCampos() {
        txf_nome.setText("");
        txf_sexo.setText("");
        txf_endereco.setText("");
        txf_cep.setText("");
        txf_bairro.setText("");
        txf_cpf.setText("");
        txf_nascimento.setText("");
        txf_dataVencimento.setText("");
        txf_unidadeConsumidora.setText("");
        txf_email.setText("");
        txf_kwh.setText("");
        txf_valorTotal.setText("");
    }

    private void habilitarFormulario(boolean status) {
        txf_nome.setEnabled(status);
        txf_sexo.setEnabled(status);
        txf_endereco.setEnabled(status);
        txf_cep.setEnabled(status);
        txf_bairro.setEnabled(status);
        txf_cpf.setEnabled(status);
        txf_nascimento.setEnabled(status);
        txf_dataVencimento.setEnabled(status);
        txf_unidadeConsumidora.setEnabled(status);
        txf_email.setEnabled(status);
        txf_kwh.setEnabled(status);
        txf_valorTotal.setEnabled(status);
        btn_salvar.setEnabled(status);
        btn_cancelar.setEnabled(status);
    }

    private void atualizarBotao(boolean status) {
        btn_alterar.setEnabled(status);
        btn_excluir.setEnabled(status);
        btn_pesquisar.setEnabled(status);
        btn_cadastrar.setEnabled(status);
        btn_cancelar.setEnabled(!status);
        btn_salvar.setEnabled(!status);
    }

    private void txf_sexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_sexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_sexoActionPerformed

    private void txf_cpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_cpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_cpfActionPerformed

    private void txf_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_nomeActionPerformed

    private void txf_bairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_bairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_bairroActionPerformed

    private void txf_cepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_cepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_cepActionPerformed

    private void btn_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alterarActionPerformed

        int linha = tabela_cliente.getSelectedRow();
        if (linha < 0) {
            JOptionPane.showMessageDialog(null, "Selecione um cliente!", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }

        atualizarBotao(false);
        habilitarFormulario(true);

        clienteSelecionado = clientes.get(linha);
        txf_nome.setText(clienteSelecionado.getNome());
        txf_sexo.setText(clienteSelecionado.getSexo());
        txf_endereco.setText(clienteSelecionado.getEndereco());
        txf_cep.setText(clienteSelecionado.getCep());
        txf_bairro.setText(clienteSelecionado.getBairro());
        txf_cpf.setText(clienteSelecionado.getCpf());
        txf_nascimento.setText(clienteSelecionado.getNascimento());
        txf_dataVencimento.setText(clienteSelecionado.getData_vencimento());
        txf_unidadeConsumidora.setText(clienteSelecionado.getUnidade_consumidora());
        txf_email.setText(clienteSelecionado.getEmail());
        txf_kwh.setText(clienteSelecionado.getKwh());
        txf_valorTotal.setText(clienteSelecionado.getValor_total());

    }//GEN-LAST:event_btn_alterarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        atualizarBotao(true);
        habilitarFormulario(false);
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pesquisarActionPerformed
        atualizarTabela();        // TODO add your handling code here:
    }//GEN-LAST:event_btn_pesquisarActionPerformed

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed

        atualizarBotao(true);
        habilitarFormulario(false);

        String nome = txf_nome.getText();//
        String sexo = txf_sexo.getText();
        String endereco = txf_endereco.getText();//
        String cep = txf_cep.getText();//
        String bairro = txf_bairro.getText();//
        String cpf = txf_cpf.getText();//
        String nascimento = txf_nascimento.getText();
        String data_vencimento = txf_dataVencimento.getText();//
        String unidade_consumidora = txf_unidadeConsumidora.getText();//
        String email = txf_email.getText();
        String kwh = txf_kwh.getText();//
        String valor_total = txf_valorTotal.getText();//

        if (nome.length() == 0) {
            JOptionPane.showMessageDialog(null, "Informe um Nome ", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (endereco.length() == 0) {
            JOptionPane.showMessageDialog(null, "Informe um Endereço ", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (cep.length() == 0) {
            JOptionPane.showMessageDialog(null, "Informe um CEP ", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (bairro.length() == 0) {
            JOptionPane.showMessageDialog(null, "Informe um Bairro ", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (cpf.length() == 0) {
            JOptionPane.showMessageDialog(null, "Informe um CPF ", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (data_vencimento.length() == 0) {
            JOptionPane.showMessageDialog(null, "Informe uma Data de Vencimento ", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (unidade_consumidora.length() == 0) {
            JOptionPane.showMessageDialog(null, "Informe uma Unidade Consumidora ", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (kwh.length() == 0) {
            JOptionPane.showMessageDialog(null, "Informe o Kw/h ", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (valor_total.length() == 0) {
            JOptionPane.showMessageDialog(null, "Informe o Valor Total ", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (clienteSelecionado == null) {
            Cliente cliente = new Cliente(nome, sexo, endereco,
                    cep, bairro, cpf, nascimento,
                    data_vencimento, unidade_consumidora, email, kwh, valor_total);

            try {
                consumoDao.adicionar(cliente);
                JOptionPane.showMessageDialog(null, "Cliente Cadastrado.");

                limparCampos();

            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "Erro na hora de inserir os dados", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            clienteSelecionado.setBairro(bairro);
            clienteSelecionado.setCep(cep);
            clienteSelecionado.setCpf(cpf);
            clienteSelecionado.setData_vencimento(data_vencimento);
            clienteSelecionado.setEmail(email);
            clienteSelecionado.setEndereco(endereco);
            clienteSelecionado.setKwh(kwh);
            clienteSelecionado.setNascimento(nascimento);
            clienteSelecionado.setNome(nome);
            clienteSelecionado.setSexo(sexo);
            clienteSelecionado.setUnidade_consumidora(unidade_consumidora);
            clienteSelecionado.setValor_total(valor_total);
            try {
                consumoDao.alterar(clienteSelecionado);
                JOptionPane.showMessageDialog(null, "Pessoa alterada");
                atualizarTabela();

            } catch (SQLException ex) {
                ex.printStackTrace();
            }

        }
        clienteSelecionado = null;
    }//GEN-LAST:event_btn_salvarActionPerformed

    private void txf_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_emailActionPerformed

    private void atualizarTabela() {
        try {
            clientes = consumoDao.buscarPeloNome(jtf_pesquisa.getText());
            DefaultTableModel model = (DefaultTableModel) tabela_cliente.getModel();
            model.setNumRows(0);

            for (int i = 0; i < clientes.size(); i++) {
                Cliente cliente = clientes.get(i);

                model.addRow(new Object[]{cliente.getNome(),
                    cliente.getCpf(), cliente.getUnidade_consumidora(),
                    cliente.getData_vencimento(), cliente.getKwh(),
                    cliente.getValor_total()});
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ConsumoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ConsumoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ConsumoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ConsumoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ConsumoForm().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_alterar;
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_pesquisar;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jtf_pesquisa;
    private javax.swing.JTable tabela_cliente;
    private javax.swing.JTextField txf_bairro;
    private javax.swing.JTextField txf_cep;
    private javax.swing.JTextField txf_cpf;
    private javax.swing.JTextField txf_dataVencimento;
    private javax.swing.JTextField txf_email;
    private javax.swing.JTextField txf_endereco;
    private javax.swing.JTextField txf_kwh;
    private javax.swing.JTextField txf_nascimento;
    private javax.swing.JTextField txf_nome;
    private javax.swing.JTextField txf_sexo;
    private javax.swing.JTextField txf_unidadeConsumidora;
    private javax.swing.JTextField txf_valorTotal;
    // End of variables declaration//GEN-END:variables

}
