/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package visao;

import modelo.Usuario;

/**
 *
 * @author aluno
 */
public class FormularioPrincipal extends javax.swing.JFrame {


    /** Creates new form FormularioPrincipal */
    public FormularioPrincipal() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jb_cliente = new javax.swing.JButton();
        l_usuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jm_manutencao = new javax.swing.JMenu();
        jmi_cliente = new javax.swing.JMenuItem();
        jmi_produtos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jb_cliente.setText("Cliente");
        jb_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_clienteActionPerformed(evt);
            }
        });

        jm_manutencao.setText("Manutenção");

        jmi_cliente.setText("Cliente");
        jmi_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_clienteActionPerformed(evt);
            }
        });
        jm_manutencao.add(jmi_cliente);

        jmi_produtos.setText("Produtos");
        jm_manutencao.add(jmi_produtos);

        jMenuBar1.add(jm_manutencao);

        jMenu2.setText("Relatórios");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jb_cliente)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_cliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmi_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_clienteActionPerformed
        ConsumoForm formPessoa = new ConsumoForm();
        formPessoa.setVisible(true);
    }//GEN-LAST:event_jmi_clienteActionPerformed

    private void jb_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_clienteActionPerformed
      ConsumoForm formPessoa = new ConsumoForm();
        formPessoa.setVisible(true);
    }//GEN-LAST:event_jb_clienteActionPerformed

        private Usuario usuario;

    public FormularioPrincipal(Usuario usuario){
        initComponents();
        this.usuario = usuario;
        l_usuario.setText("Usuario logado: "+ usuario.getNome());
        controleNivelAcesso();
    }
    
    private void controleNivelAcesso(){
        if(this.usuario.getNivel().equals("admin")){
            this.jm_manutencao.setVisible(true);
            this.jMenu2.setVisible(true);
        }else{
            this.jm_manutencao.setVisible(true);
            this.jMenu2.setVisible(false);

        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton jb_cliente;
    private javax.swing.JMenu jm_manutencao;
    private javax.swing.JMenuItem jmi_cliente;
    private javax.swing.JMenuItem jmi_produtos;
    private javax.swing.JLabel l_usuario;
    // End of variables declaration//GEN-END:variables

}
